# Generated by Django 6.0.6 on 2026-07-01 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('add_funds', 'Add Funds'), ('internet_phone', 'Internet & Phone'), ('office_supplies', 'Office Supplies'), ('team_meals', 'Team Meals & Meetings'), ('software_tools', 'Software Tools & Subscriptions'), ('salaries', 'Salaries & Allowances'), ('rent', 'Rent/Co-working Space'), ('grants_donations', 'Grants / Donations Received'), ('transfers', 'Transfers')], max_length=100),
        ),
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('add_funds', 'Add Funds'), ('internet_phone', 'Internet & Phone'), ('office_supplies', 'Office Supplies'), ('team_meals', 'Team Meals & Meetings'), ('software_tools', 'Software Tools & Subscriptions'), ('salaries', 'Salaries & Allowances'), ('rent', 'Rent/Co-working Space'), ('grants_donations', 'Grants / Donations Received'), ('transfers', 'Transfers')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spend_link', to='expenses.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spends', to='expenses.wallet')),
            ],
            options={
                'db_table': 'spends',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='spend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_ref', to='expenses.spend'),
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='expenses.wallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='expenses.wallet')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transfer_link', to='expenses.transaction')),
            ],
            options={
                'db_table': 'wallet_transfers',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_ref', to='expenses.wallettransfer'),
        ),
    ]
