# Generated by Django 6.0.6 on 2026-07-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='wallet_balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='spend',
            name='category',
            field=models.CharField(choices=[('capital_injection', 'Capital Injection'), ('generic_income', 'Generic'), ('grants_donations', 'Grants / Donations Received'), ('internet_phone', 'Internet & Phone'), ('office_supplies', 'Office Supplies'), ('team_meals', 'Team Meals & Meetings'), ('software_tools', 'Software Tools & Subscriptions'), ('salaries', 'Salaries & Allowances'), ('rent', 'Rent/Co-working Space'), ('transfers', 'Transfers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('capital_injection', 'Capital Injection'), ('generic_income', 'Generic'), ('grants_donations', 'Grants / Donations Received'), ('internet_phone', 'Internet & Phone'), ('office_supplies', 'Office Supplies'), ('team_meals', 'Team Meals & Meetings'), ('software_tools', 'Software Tools & Subscriptions'), ('salaries', 'Salaries & Allowances'), ('rent', 'Rent/Co-working Space'), ('transfers', 'Transfers')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('add funds', 'Add Funds'), ('spend funds', 'Spend Funds'), ('transfer out', 'Transfer Out'), ('transfer in', 'Transfer In')], max_length=20),
        ),
    ]
