# Generated by Django 6.0.6 on 2026-06-25 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_days_worked', models.IntegerField(default=0)),
                ('total_absences', models.IntegerField(default=0)),
                ('payment_type', models.CharField(max_length=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overtime_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_additions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('logged_to_expenses', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtr_id', models.IntegerField(unique=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], default='hourly', max_length=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('addition', 'Addition'), ('deduction', 'Deduction')], max_length=10)),
                ('category', models.CharField(choices=[('bonus', 'Bonus'), ('cash_advance', 'Cash Advance Repayment'), ('overtime_premium', 'Overtime Premium'), ('allowance', 'Allowance'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payrollentry')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('total_gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source_wallet', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollrun'),
        ),
        migrations.CreateModel(
            name='TimesheetSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('morning_time_in', models.CharField(blank=True, max_length=10, null=True)),
                ('morning_time_out', models.CharField(blank=True, max_length=10, null=True)),
                ('morning_hours', models.FloatField(default=0)),
                ('afternoon_time_in', models.CharField(blank=True, max_length=10, null=True)),
                ('afternoon_time_out', models.CharField(blank=True, max_length=10, null=True)),
                ('afternoon_hours', models.FloatField(default=0)),
                ('overtime_time_in', models.CharField(blank=True, max_length=10, null=True)),
                ('overtime_time_out', models.CharField(blank=True, max_length=10, null=True)),
                ('overtime_hours', models.FloatField(default=0)),
                ('total_hours', models.FloatField(default=0)),
                ('is_holiday', models.BooleanField(default=False)),
                ('holiday_type', models.CharField(blank=True, choices=[('regular', 'Regular Holiday'), ('special_non_working', 'Special Non-Working'), ('special_working', 'Special Working')], max_length=30, null=True)),
                ('holiday_name', models.CharField(blank=True, max_length=100, null=True)),
                ('face_verified', models.BooleanField(default=False)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheet_syncs', to='payroll.worker')),
            ],
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.worker'),
        ),
    ]
